package net.cdahmedeh.poetwrite.ui.syntax;

import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.AbstractTokenMaker;
import org.fife.ui.rsyntaxtextarea.Token;
import org.fife.ui.rsyntaxtextarea.TokenMap;

/**
 * TokenMaker for the PoetWrite poem format. Used by RSyntaxTextArea for
 * syntax-highlighting without using a theme file.
 *
 * DISCLOSURE: Some of this code was generated by Claude. It was fed the ANTLR
 *             grammar.
 *
 * Mirrors the Poem.g4 grammar:
 *   WORD        : [A-Za-z0-9'-]+
 *   PUNCTUATION : [.,!?]
 *   SPACE       : [ ]+
 *   note        : '[' token+ ']'
 *   aside       : '(' token+ ')'
 *
 * Token type mapping:
 *   notes  [..]  -> COMMENT_MULTILINE (content) + SEPARATOR (brackets)
 *   asides (..)  -> LITERAL_STRING_DOUBLE_QUOTE (content) + SEPARATOR (parens)
 *   words        -> IDENTIFIER
 *   punctuation  -> OPERATOR
 *   spaces       -> WHITESPACE
 *   anything not in the grammar -> ERROR_CHAR
 *
 * Notes and asides are line-scoped (the grammar never lets them cross a
 * NEWLINE), so this lexer keeps no cross-line state and always ends the
 * line with addNullToken().
 */
public class PoemTokenMaker extends AbstractTokenMaker {

    private static final int CTX_NORMAL = 0;
    private static final int CTX_NOTE   = 1;
    private static final int CTX_ASIDE  = 2;

    @Override
    public TokenMap getWordsToHighlight() {
        // The poem language has no keywords.
        return new TokenMap();
    }

    private static boolean isWordChar(char c) {
        return (c >= 'A' && c <= 'Z')
                || (c >= 'a' && c <= 'z')
                || (c >= '0' && c <= '9')
                || c == '\''
                || c == '-';
    }

    private static boolean isPunctuation(char c) {
        return c == '.' || c == ',' || c == '!' || c == '?';
    }

    /**
     * Content inside a note or aside is recolored wholesale so the whole
     * construct reads as one visual unit; outside them, the token keeps
     * its natural type.
     */
    private static int typeFor(int context, int normalType) {
        switch (context) {
            case CTX_NOTE:  return Token.COMMENT_MULTILINE;
            case CTX_ASIDE: return Token.LITERAL_STRING_DOUBLE_QUOTE;
            default:        return normalType;
        }
    }

    @Override
    public Token getTokenList(Segment text, int initialTokenType, int startOffset) {
        resetTokenList();

        char[] array = text.array;
        int offset   = text.offset;
        int end      = offset + text.count;

        // Delta between position-in-array and position-in-document.
        int newStartOffset = startOffset - offset;

        int context = CTX_NORMAL;
        int i = offset;

        while (i < end) {
            char c = array[i];
            int tokenStart = i;

            switch (c) {
                case '[':
                    addToken(text, i, i, Token.SEPARATOR, newStartOffset + i);
                    context = CTX_NOTE;
                    i++;
                    break;

                case ']':
                    addToken(text, i, i, Token.SEPARATOR, newStartOffset + i);
                    context = CTX_NORMAL;
                    i++;
                    break;

                case '(':
                    addToken(text, i, i, Token.SEPARATOR, newStartOffset + i);
                    context = CTX_ASIDE;
                    i++;
                    break;

                case ')':
                    addToken(text, i, i, Token.SEPARATOR, newStartOffset + i);
                    context = CTX_NORMAL;
                    i++;
                    break;

                case ' ':
                    while (i < end && array[i] == ' ') {
                        i++;
                    }
                    addToken(text, tokenStart, i - 1,
                            typeFor(context, Token.WHITESPACE),
                            newStartOffset + tokenStart);
                    break;

                default:
                    if (isWordChar(c)) {
                        while (i < end && isWordChar(array[i])) {
                            i++;
                        }
                        addToken(text, tokenStart, i - 1,
                                typeFor(context, Token.IDENTIFIER),
                                newStartOffset + tokenStart);
                    } else if (isPunctuation(c)) {
                        while (i < end && isPunctuation(array[i])) {
                            i++;
                        }
                        addToken(text, tokenStart, i - 1,
                                typeFor(context, Token.OPERATOR),
                                newStartOffset + tokenStart);
                    } else {
                        // Character the grammar doesn't allow (e.g. ; : " —).
                        // Flag it so grammar violations are visible in the editor.
                        addToken(text, i, i, Token.ERROR_CHAR, newStartOffset + i);
                        i++;
                    }
                    break;
            }
        }

        // No construct spans lines, so every line ends in the default state.
        addNullToken();
        return firstToken;
    }
}